### ISSUE TITLE
Fix time/date-based output tests to prevent inconsistent test results

### ISSUE THREAD

**Issue by Cherry** [nodecraft/spawnpoint#20]
Looking at https://travis-ci.org/nodecraft/spawnpoint/builds/584216421, tests sometimes fail inconsistently due to how we're testing console output with variable times/dates.

As an example at https://travis-ci.org/nodecraft/spawnpoint/jobs/584216430, you can see we expected `[16:05] [WARN]: Test`, but instead saw `[16:06] [WARN]: Test` as the test took slightly longer to run.

The tests that need to be tweaked to allow dates/times in the future slightly (or ignore the time prefix) are at https://github.com/nodecraft/spawnpoint/blob/master/test/output.js.

This should close #19 and close #18 and close #16 and close #13 and close #12.

**Comment by mhoobler** [comment]
I made a very simple bandaid solution (it basically replaces the time from the data being tested with the time the test sees). I wanted to go a step further and have it make sure the time from the data is only a minute behind, but it'd be a lot more code added to the test file and I'm wondering if that would be a problem, I'm not incredibly familiar with testing in Node.

**Comment by Cherry** [comment]
Awesome job @mhoobler! More code being added to the test file is totally fine - the aim is to test the framework. Just submit a PR when you're ready. 😃

**Comment by mhoobler** [comment]
I made the pull request. If there's any changes that you need please let me know. Also, thanks for the opportunity it was a fun first issue! 😄

**Comment by Cherry** [comment]
Congrats on your first contribution @mhoobler, that's awesome! I hope you reach the 4 PRs for Hacktoberfest.

I've left a few comments over on #22 - let me know if you have any questions.

**Comment by Cherry** [comment]
Closed by #22
