### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by Cherry** [nodecraft/spawnpoint#21]
Travis is currently used for CI, but we can switch to GitHub Actions.

Please see https://github.com/nodecraft/b2-cloud-storage/pull/14 for details on what needs to be included.

- Workflow test.yml - needs tweaks to support testing on more than just Linux
- Readme badge
- package.json updates for code-coverage (no longer pipe `coverage` to `coveralls` and instead just generate report in `lcov` format, and then upload using an Actions step)

**Comment by adityaarakeri** [comment]
can take this up. watch for a PR

**Comment by Cherry** [comment]
Awesome @adityaarakeri , thanks for wanting to contribute!

Awaiting your PR. Good luck on reaching your 4 PRs for Hacktoberfest!

PS. We have quite a few other repos that could use switching over too if you're interested in those; https://github.com/issues?q=is%3Aissue+org%3Anodecraft+label%3Ahacktoberfest+is%3Aopen

**Comment by Cherry** [comment]
Closed by #23
